import AppContext from "@/context/AppContext";
import Authprovider from "./(authprovider)/AuthProvider";
import "./globals.css";
import { Header } from "@/components/Headers";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppContext>
          <Authprovider>
            <Header />
            {children}
            <ToastContainer />
          </Authprovider>
        </AppContext>
      </body>
    </html>
  );
}
